version: "3.8"
services:
   br-fedora37:
    build:
      context: ./
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    privileged: true
    stdin_open: true
    tty: true
    image: br-fedora37:latest
    container_name:  br-fedora37
