version: "3.7"
services:
   example-buildroot-project-build:
    build:
      context: ./
      args:
         BUILDROOT_USER: br-user
         BUILDROOT_DIR: buildroot
         COMPANY_NAMES: my_company my_other_company
         BUILDROOT_PATCH_DIR: ""
         UID: 1000
         GID: 1000
    env_file:
      - docker/env
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./:/mnt
      - example-buildroot-project-build-ccache:/home/ccache
    image: example-buildroot-project-build:latest
    container_name:  example-buildroot-project-build
volumes:
  example-buildroot-project-build-ccache:
