version: "3.7"
services:
   example-buildroot-project-build:
    build:
      context: ./
    env_file:
      - docker/env
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./:/mnt
      - example-buildroot-project-build-ccache:/home/br-user/ccache
    image: example-buildroot-project-build:latest
    container_name:  example-buildroot-project-build
volumes:
  example-buildroot-project-build-ccache:
