version: "3.7"
services:
   br-ubuntu19.10:
    build:
      context: ./
    environment:
      - TZ=America/Los_Angeles
      - DEBIAN_FRONTEND=noninteractive
    privileged: true
    stdin_open: true
    tty: true
    image: br-ubuntu19.10:latest
    container_name:  br-ubuntu19.10
